-- MySQL Script generated by MySQL Workbench
-- Wed May 30 15:45:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema DBBANCO
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DBBANCO` ;
CREATE SCHEMA IF NOT EXISTS `DBBANCO` DEFAULT CHARACTER SET utf8 ;
USE `DBBANCO` ;

-- -----------------------------------------------------
-- Table `DBBANCO`.`CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBANCO`.`CLIENTE` ;

CREATE TABLE IF NOT EXISTS `DBBANCO`.`CLIENTE` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cadastroDatetime` DATETIME NOT NULL,
  `endereco` VARCHAR(64) NULL,
  `nome` VARCHAR(64) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBANCO`.`FISICO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBANCO`.`FISICO` ;

CREATE TABLE IF NOT EXISTS `DBBANCO`.`FISICO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(11) NOT NULL,
  `cliente` INT NOT NULL,
  PRIMARY KEY (`id`, `cpf`),
  INDEX `fk_FISICO_CLIENTE1_idx` (`cliente` ASC),
  CONSTRAINT `fk_FISICO_CLIENTE1`
    FOREIGN KEY (`cliente`)
    REFERENCES `DBBANCO`.`CLIENTE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBANCO`.`JURIDICO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBANCO`.`JURIDICO` ;

CREATE TABLE IF NOT EXISTS `DBBANCO`.`JURIDICO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(64) NOT NULL,
  `cliente` INT NOT NULL,
  PRIMARY KEY (`id`, `cnpj`),
  INDEX `fk_JURIDICO_CLIENTE1_idx` (`cliente` ASC),
  CONSTRAINT `fk_JURIDICO_CLIENTE1`
    FOREIGN KEY (`cliente`)
    REFERENCES `DBBANCO`.`CLIENTE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBANCO`.`OPERACAO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBANCO`.`OPERACAO` ;

CREATE TABLE IF NOT EXISTS `DBBANCO`.`OPERACAO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `operacao` INT NOT NULL,
  `fisico` INT NULL,
  `fisicoCPF` VARCHAR(11) NULL,
  `juridico` INT NULL,
  `juridicoCNPJ` VARCHAR(64) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_OPERACAO_FISICO1_idx` (`fisico` ASC, `fisicoCPF` ASC),
  INDEX `fk_OPERACAO_JURIDICO1_idx` (`juridico` ASC, `juridicoCNPJ` ASC),
  CONSTRAINT `fk_OPERACAO_FISICO1`
    FOREIGN KEY (`fisico` , `fisicoCPF`)
    REFERENCES `DBBANCO`.`FISICO` (`id` , `cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OPERACAO_JURIDICO1`
    FOREIGN KEY (`juridico` , `juridicoCNPJ`)
    REFERENCES `DBBANCO`.`JURIDICO` (`id` , `cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBANCO`.`CONTA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBANCO`.`CONTA` ;

CREATE TABLE IF NOT EXISTS `DBBANCO`.`CONTA` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `conta` VARCHAR(9) NOT NULL,
  `cadastroDatetime` DATETIME NOT NULL,
  `senha` VARCHAR(256) NOT NULL,
  `saldo` INT NULL,
  `operacao` INT NOT NULL,
  PRIMARY KEY (`id`, `conta`, `operacao`),
  INDEX `fk_CONTA_OPERACAO1_idx` (`operacao` ASC),
  CONSTRAINT `fk_CONTA_OPERACAO1`
    FOREIGN KEY (`operacao`)
    REFERENCES `DBBANCO`.`OPERACAO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBANCO`.`TELEFONE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBANCO`.`TELEFONE` ;

CREATE TABLE IF NOT EXISTS `DBBANCO`.`TELEFONE` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `telefone` VARCHAR(13) NOT NULL,
  `cliente` INT NOT NULL,
  PRIMARY KEY (`id`, `telefone`, `cliente`),
  INDEX `fk_TELEFONE_CLIENTE1_idx` (`cliente` ASC),
  CONSTRAINT `fk_TELEFONE_CLIENTE1`
    FOREIGN KEY (`cliente`)
    REFERENCES `DBBANCO`.`CLIENTE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBANCO`.`AGENCIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBANCO`.`AGENCIA` ;

CREATE TABLE IF NOT EXISTS `DBBANCO`.`AGENCIA` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `endereco` VARCHAR(64) NULL,
  `nome` VARCHAR(64) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBANCO`.`ADMINISTRADOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBANCO`.`ADMINISTRADOR` ;

CREATE TABLE IF NOT EXISTS `DBBANCO`.`ADMINISTRADOR` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(256) NOT NULL UNIQUE,
  `senha` VARCHAR(256) NOT NULL,
  `agencia` INT NOT NULL,
  PRIMARY KEY (`id`, `agencia`, `login`),
  INDEX `fk_ADMINISTRADOR_AGENCIA_idx` (`agencia` ASC),
  CONSTRAINT `fk_ADMINISTRADOR_AGENCIA`
    FOREIGN KEY (`agencia`)
    REFERENCES `DBBANCO`.`AGENCIA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBANCO`.`FUNCIONARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBANCO`.`FUNCIONARIO` ;

CREATE TABLE IF NOT EXISTS `DBBANCO`.`FUNCIONARIO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cadastroDatetime` DATETIME NOT NULL,
  `login` VARCHAR(256) NOT NULL UNIQUE,
  `senha` VARCHAR(256) NOT NULL,
  `administrador` INT NOT NULL,
  PRIMARY KEY (`id`, `administrador`, `login`),
  INDEX `fk_FUNCIONARIO_ADMINISTRADOR1_idx` (`administrador` ASC),
  CONSTRAINT `fk_FUNCIONARIO_ADMINISTRADOR1`
    FOREIGN KEY (`administrador`)
    REFERENCES `DBBANCO`.`ADMINISTRADOR` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBANCO`.`TRANSACAO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBANCO`.`TRANSACAO` ;

CREATE TABLE IF NOT EXISTS `DBBANCO`.`TRANSACAO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datetime` DATETIME NULL,
  `valor` INT NOT NULL,
  `origemConta` INT NOT NULL,
  `origemContaConta` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id`, `origemConta`, `origemContaConta`),
  INDEX `fk_TRANSACAO_CONTA1_idx` (`origemConta` ASC, `origemContaConta` ASC),
  CONSTRAINT `fk_TRANSACAO_CONTA1`
    FOREIGN KEY (`origemConta` , `origemContaConta`)
    REFERENCES `DBBANCO`.`CONTA` (`id` , `conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBANCO`.`TRANSFERENCIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBANCO`.`TRANSFERENCIA` ;

CREATE TABLE IF NOT EXISTS `DBBANCO`.`TRANSFERENCIA` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datetime` DATETIME NULL,
  `origemTransacao` INT NOT NULL,
  `destinoConta` INT NOT NULL,
  `destinoContaConta` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id`, `origemTransacao`, `destinoConta`, `destinoContaConta`),
  INDEX `fk_TRANSFERENCIA_TRANSACAO1_idx` (`origemTransacao` ASC),
  INDEX `fk_TRANSFERENCIA_CONTA1_idx` (`destinoConta` ASC, `destinoContaConta` ASC),
  CONSTRAINT `fk_TRANSFERENCIA_TRANSACAO1`
    FOREIGN KEY (`origemTransacao`)
    REFERENCES `DBBANCO`.`TRANSACAO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRANSFERENCIA_CONTA1`
    FOREIGN KEY (`destinoConta` , `destinoContaConta`)
    REFERENCES `DBBANCO`.`CONTA` (`id` , `conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBANCO`.`SERVICO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBANCO`.`SERVICO` ;

CREATE TABLE IF NOT EXISTS `DBBANCO`.`SERVICO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cadastroDatetime` DATETIME NOT NULL,
  `tipo` INT NOT NULL,
  `valor` INT NOT NULL,
  `descricao` VARCHAR(1024) NULL,
  `administrador` INT NULL,
  `funcionario` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_SERVICO_FUNCIONARIO1_idx` (`funcionario` ASC),
  CONSTRAINT `fk_SERVICO_ADMINISTRADOR1`
    FOREIGN KEY (`administrador`)
    REFERENCES `DBBANCO`.`ADMINISTRADOR` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SERVICO_FUNCIONARIO1`
    FOREIGN KEY (`funcionario`)
    REFERENCES `DBBANCO`.`FUNCIONARIO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBANCO`.`PAGAMENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBANCO`.`PAGAMENTO` ;

CREATE TABLE IF NOT EXISTS `DBBANCO`.`PAGAMENTO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `metodo` INT NOT NULL,
  `servico` INT NOT NULL,
  `transacao` INT NOT NULL,
  PRIMARY KEY (`id`, `servico`, `transacao`),
  INDEX `fk_PAGAMENTO_TRANSACAO1_idx` (`transacao` ASC),
  CONSTRAINT `fk_PAGAMENTO_SERVICO1`
    FOREIGN KEY (`servico`)
    REFERENCES `DBBANCO`.`SERVICO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PAGAMENTO_TRANSACAO1`
    FOREIGN KEY (`transacao`)
    REFERENCES `DBBANCO`.`TRANSACAO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBANCO`.`AUTORIZA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBANCO`.`AUTORIZA` ;

CREATE TABLE IF NOT EXISTS `DBBANCO`.`AUTORIZA` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `funcionario` INT NOT NULL,
  `cliente` INT NOT NULL,
  PRIMARY KEY (`id`, `funcionario`, `cliente`),
  INDEX `fk_AUTORIZA_CLIENTE1_idx` (`cliente` ASC),
  CONSTRAINT `fk_AUTORIZA_FUNCIONARIO1`
    FOREIGN KEY (`funcionario`)
    REFERENCES `DBBANCO`.`FUNCIONARIO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AUTORIZA_CLIENTE1`
    FOREIGN KEY (`cliente`)
    REFERENCES `DBBANCO`.`CLIENTE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

