-- MySQL Script generated by MySQL Workbench
-- Tue May 22 01:37:49 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DBBANCO
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DBBANCO` ;

-- -----------------------------------------------------
-- Schema DBBANCO
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DBBANCO` DEFAULT CHARACTER SET utf8 ;
USE `DBBANCO` ;

-- -----------------------------------------------------
-- Table `DBBANCO`.`CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBANCO`.`CLIENTE` ;

CREATE TABLE IF NOT EXISTS `DBBANCO`.`CLIENTE` (
  `id` INT NOT NULL,
  `cadastroDatetime` DATETIME NOT NULL,
  `endereco` VARCHAR(64) NULL,
  `nome` VARCHAR(64) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBANCO`.`FISICO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBANCO`.`FISICO` ;

CREATE TABLE IF NOT EXISTS `DBBANCO`.`FISICO` (
  `cpf` VARCHAR(11) NOT NULL,
  `cliente` INT NOT NULL,
  PRIMARY KEY (`cpf`, `cliente`),
  INDEX `fk_FISICO_CLIENTE1_idx` (`cliente` ASC),
  CONSTRAINT `fk_FISICO_CLIENTE1`
    FOREIGN KEY (`cliente`)
    REFERENCES `DBBANCO`.`CLIENTE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBANCO`.`JURIDICO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBANCO`.`JURIDICO` ;

CREATE TABLE IF NOT EXISTS `DBBANCO`.`JURIDICO` (
  `cnpj` VARCHAR(64) NOT NULL,
  `cliente` INT NOT NULL,
  PRIMARY KEY (`cnpj`, `cliente`),
  INDEX `fk_JURIDICO_CLIENTE1_idx` (`cliente` ASC),
  CONSTRAINT `fk_JURIDICO_CLIENTE1`
    FOREIGN KEY (`cliente`)
    REFERENCES `DBBANCO`.`CLIENTE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBANCO`.`OPERACAO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBANCO`.`OPERACAO` ;

CREATE TABLE IF NOT EXISTS `DBBANCO`.`OPERACAO` (
  `operacao` INT NOT NULL,
  `cpf` VARCHAR(11) NULL,
  `cnpj` VARCHAR(64) NULL,
  PRIMARY KEY (`operacao`),
  INDEX `fk_OPERACAO_FISICO1_idx` (`cpf` ASC),
  INDEX `fk_OPERACAO_JURIDICO1_idx` (`cnpj` ASC),
  CONSTRAINT `fk_OPERACAO_FISICO1`
    FOREIGN KEY (`cpf`)
    REFERENCES `DBBANCO`.`FISICO` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OPERACAO_JURIDICO1`
    FOREIGN KEY (`cnpj`)
    REFERENCES `DBBANCO`.`JURIDICO` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBANCO`.`CONTA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBANCO`.`CONTA` ;

CREATE TABLE IF NOT EXISTS `DBBANCO`.`CONTA` (
  `id` VARCHAR(9) NOT NULL,
  `saldo` INT NULL,
  `senha` VARCHAR(256) NULL,
  `operacao` INT NOT NULL,
  PRIMARY KEY (`id`, `operacao`),
  INDEX `fk_CONTA_OPERACAO1_idx` (`operacao` ASC),
  CONSTRAINT `fk_CONTA_OPERACAO1`
    FOREIGN KEY (`operacao`)
    REFERENCES `DBBANCO`.`OPERACAO` (`operacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBANCO`.`TELEFONE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBANCO`.`TELEFONE` ;

CREATE TABLE IF NOT EXISTS `DBBANCO`.`TELEFONE` (
  `telefone` VARCHAR(13) NOT NULL,
  `cliente` INT NOT NULL,
  PRIMARY KEY (`telefone`, `cliente`),
  INDEX `fk_TELEFONE_CLIENTE1_idx` (`cliente` ASC),
  CONSTRAINT `fk_TELEFONE_CLIENTE1`
    FOREIGN KEY (`cliente`)
    REFERENCES `DBBANCO`.`CLIENTE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBANCO`.`AGENCIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBANCO`.`AGENCIA` ;

CREATE TABLE IF NOT EXISTS `DBBANCO`.`AGENCIA` (
  `id` INT NOT NULL,
  `endereco` VARCHAR(64) NULL,
  `nome` VARCHAR(64) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBANCO`.`ADMINISTRADOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBANCO`.`ADMINISTRADOR` ;

CREATE TABLE IF NOT EXISTS `DBBANCO`.`ADMINISTRADOR` (
  `id` INT NOT NULL,
  `login` VARCHAR(256) NULL,
  `senha` VARCHAR(256) NULL,
  `agencia` INT NOT NULL,
  PRIMARY KEY (`id`, `agencia`),
  INDEX `fk_ADMINISTRADOR_AGENCIA_idx` (`agencia` ASC),
  CONSTRAINT `fk_ADMINISTRADOR_AGENCIA`
    FOREIGN KEY (`agencia`)
    REFERENCES `DBBANCO`.`AGENCIA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBANCO`.`FUNCIONARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBANCO`.`FUNCIONARIO` ;

CREATE TABLE IF NOT EXISTS `DBBANCO`.`FUNCIONARIO` (
  `id` INT NOT NULL,
  `login` VARCHAR(256) NOT NULL,
  `senha` VARCHAR(256) NOT NULL,
  `administrador` INT NOT NULL,
  PRIMARY KEY (`id`, `administrador`),
  INDEX `fk_FUNCIONARIO_ADMINISTRADOR1_idx` (`administrador` ASC),
  CONSTRAINT `fk_FUNCIONARIO_ADMINISTRADOR1`
    FOREIGN KEY (`administrador`)
    REFERENCES `DBBANCO`.`ADMINISTRADOR` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBANCO`.`TRANSACAO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBANCO`.`TRANSACAO` ;

CREATE TABLE IF NOT EXISTS `DBBANCO`.`TRANSACAO` (
  `id` INT NOT NULL,
  `valor` INT NULL,
  `datetime` DATETIME NULL,
  `origemConta` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id`, `origemConta`),
  INDEX `fk_TRANSACAO_CONTA1_idx` (`origemConta` ASC),
  CONSTRAINT `fk_TRANSACAO_CONTA1`
    FOREIGN KEY (`origemConta`)
    REFERENCES `DBBANCO`.`CONTA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBANCO`.`TRANSFERENCIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBANCO`.`TRANSFERENCIA` ;

CREATE TABLE IF NOT EXISTS `DBBANCO`.`TRANSFERENCIA` (
  `destinoConta` VARCHAR(9) NOT NULL,
  `origemTransacao` INT NOT NULL,
  PRIMARY KEY (`destinoConta`, `origemTransacao`),
  INDEX `fk_TRANSFERENCIA_TRANSACAO1_idx` (`origemTransacao` ASC),
  CONSTRAINT `fk_TRANSFERENCIA_CONTA1`
    FOREIGN KEY (`destinoConta`)
    REFERENCES `DBBANCO`.`CONTA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRANSFERENCIA_TRANSACAO1`
    FOREIGN KEY (`origemTransacao`)
    REFERENCES `DBBANCO`.`TRANSACAO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBANCO`.`SERVICO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBANCO`.`SERVICO` ;

CREATE TABLE IF NOT EXISTS `DBBANCO`.`SERVICO` (
  `id` INT NOT NULL,
  `tipo` INT NULL,
  `valor` INT NULL,
  `descricao` VARCHAR(1024) NULL,
  `administrador` INT NULL,
  `funcionario` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_SERVICO_FUNCIONARIO1_idx` (`funcionario` ASC),
  CONSTRAINT `fk_SERVICO_ADMINISTRADOR1`
    FOREIGN KEY (`administrador`)
    REFERENCES `DBBANCO`.`ADMINISTRADOR` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SERVICO_FUNCIONARIO1`
    FOREIGN KEY (`funcionario`)
    REFERENCES `DBBANCO`.`FUNCIONARIO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBANCO`.`PAGAMENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBANCO`.`PAGAMENTO` ;

CREATE TABLE IF NOT EXISTS `DBBANCO`.`PAGAMENTO` (
  `metodo` INT NOT NULL,
  `servico` INT NOT NULL,
  `transacao` INT NOT NULL,
  PRIMARY KEY (`servico`, `transacao`),
  INDEX `fk_PAGAMENTO_TRANSACAO1_idx` (`transacao` ASC),
  CONSTRAINT `fk_PAGAMENTO_SERVICO1`
    FOREIGN KEY (`servico`)
    REFERENCES `DBBANCO`.`SERVICO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PAGAMENTO_TRANSACAO1`
    FOREIGN KEY (`transacao`)
    REFERENCES `DBBANCO`.`TRANSACAO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBBANCO`.`AUTORIZA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBBANCO`.`AUTORIZA` ;

CREATE TABLE IF NOT EXISTS `DBBANCO`.`AUTORIZA` (
  `funcionario` INT NOT NULL,
  `cliente` INT NOT NULL,
  PRIMARY KEY (`funcionario`, `cliente`),
  INDEX `fk_AUTORIZA_CLIENTE1_idx` (`cliente` ASC),
  CONSTRAINT `fk_AUTORIZA_FUNCIONARIO1`
    FOREIGN KEY (`funcionario`)
    REFERENCES `DBBANCO`.`FUNCIONARIO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AUTORIZA_CLIENTE1`
    FOREIGN KEY (`cliente`)
    REFERENCES `DBBANCO`.`CLIENTE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
